site_name: ISO-TP (ISO 15765-2)
site_description: ISO-TP protocol implementation in C
site_author: Anton Vynohradov
repo_url: https://github.com/AntonVynohradov/isotp-c
edit_uri: ""
site_url: https://AntonVynohradov.github.io/isotp-c/

nav:
  - Home: index.md
  - Getting Started: guide.md
  - Configuration: configuration.md
  - API Reference: api.md
  - License: LICENSE.md
  - Examples:
      - Linux SocketCAN: examples/linux_socket.md
      - Python API: examples/python_api.md
  - Integration Tests:
      - ISO-15765 Project Structure: iso_15765_project_structure.md

theme:
  name: readthedocs
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - autorefs
  - mkdoxy:
      projects:
        docs:
          src-dirs: .
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.c *.h* *.cpp *.py"
            RECURSIVE: True

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - admonition
  - tables
