name: Google Unit Tests

on:
  workflow_run:
    workflows: ["Check Building Static Library"]
    types:
      - completed

jobs:
  unit-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Google Test and gcovr
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev gcovr

      - name: Configure (UnitTests preset)
        run: cmake --preset "ISO-TP[UnitTests]" -B "build/ISO-TP[UnitTests]"

      - name: Build (coverage)
        run: cmake --build "build/ISO-TP[UnitTests]" --target coverage

      - name: Test
        run: ctest --test-dir "build/ISO-TP[UnitTests]" --output-on-failure

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/ISO-TP\[UnitTests\]/Coverage
