name: Google Unit Tests

on:
  workflow_run:
    workflows: ["Check Building Static Library"]
    types:
      - completed

jobs:
  unit-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         

      - name: Configure (UnitTests preset)
        run: cmake --preset "ISO-TP[UnitTests]" -B "build/ISO-TP[UnitTests]"

      - name: Build
        run: cmake --build "build/ISO-TP[UnitTests]"

      - name: Test
        run: ctest --test-dir "build/ISO-TP[UnitTests]" --output-on-failure
