name: Python Integration Tests

on:
  workflow_run:
    workflows: ["Check Building Static Library"]
    types:
      - completed

jobs:
  integration-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.pull_requests[0].head.sha || github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pytest
        run: python -m pip install --upgrade pip pytest

      - name: Configure (Python C API)
        run: cd examples/python_api && cmake -G "Unix Makefiles" -B build -DISOTP_INTEGRATION_TESTS=ON

      - name: Build (Integration Tests)
        run: cd examples/python_api && cmake --build build --target integration_tests
